development:
  adapter: postgresql
  encoding: unicode
  database: gaidarfund_project
  pool: 5

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: gaidarfund_project
  pool: 5
  username: gaidarfund_project
  password: eqd_ew3s_sd3kic