development:
  adapter: postgresql
  encoding: unicode
  database: gaidarfund_project
  pool: 5
  username: gaidarfund_project
  password: eqd_ew3s_sd3kic

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gaidarfund
  pool: 5
  username: gaidarfund
  password: w43i_2s7irtguw