production:
  morphology: stem_enru, soundex, metaphone
  charset_table: 0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+401->U+451,U+451->U+435
development:
  morphology: stem_enru, soundex, metaphone
  charset_table: 0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+401->U+451,U+451->U+435